version: "3.8"

services:
  glitchandbooks:
    image: glitchandbooks
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db-glitchandbooks
    networks:
      - traefik
      - glitchandbooks
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.glitchandbooks.rule=Host(`test.homeserver-ericp.fr`)"
      - "traefik.http.routers.glitchandbooks.entrypoints=websecure"
      - "traefik.http.routers.glitchandbooks.tls=true"
      - "traefik.http.services.glitchandbooks.loadbalancer.server.port=80"
      - "traefik.http.routers.glitchandbooks.tls.certresolver=myresolver"
      - "traefik.docker.network=traefik"

  db-glitchandbooks:
    image: postgres:13
    container_name: db-glitchandbooks
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    networks:
      - glitchandbooks
    volumes:
      - pgdata-glitchandbooks:/var/lib/postgresql/data

networks:
  traefik:
    external: true
  glitchandbooks:
    driver: bridge
